---
title: "Likelihood of the 2025 Hall of Fame Ballot Being Inducted"
output:
  pdf_document: default
  html_notebook: default
editor_options:
  markdown:
    wrap: 100
---

<font size="5">Hitters' Benchmarks: (Black Ink: 27, HOF Standards: 50, HOF Monitor: 100)</font>

**Alex Rodriguez (65, 84, 383):** By any and all statistical measures, Alex Rodriguez is a sure-fire
100% Hall of Fame (HOF) lock. He far surpasses even the average Hall of Famer by the Black Ink test,
the Hall of Fame Monitor, and the Hall of Fame Standards. The quality of play on the field is
unquestionably worthy of first-ballot Hall of Fame consideration, however A-Rod’s association with
PED use on multiple occasions (admittance of steroid use during his Rangers stint and links to
Biogenesis program in 2013) is souring the minds of 65.2% of voters in his fourth year on the
ballot.

**Ichiro (37, 46, 231.5):** Ichiro is the only player on the ballot that can be considered a lock
for the Hall in 2025. In his first trip on the ballot, Ichiro will surely approach Mariano Rivera’s
unanimous selection in 2019. The Black Ink test and the Hall of Fame Monitor support Ichiro’s case,
but the Hall of Fame Standards rate Ichiro lower than the average Hall of Famer. This is likely due
to the fact that Ichiro did not begin his MLB career until the age of 27, missing out on five to six
years of his prime.

**Manny Ramirez (21, 69, 243.5):** Similar to Alex Rodriguez, Manny Ramirez’s Hall of Fame case is
hindered by his suspensions from PED usage at the end of his career. While the Black Ink score is
lower than average (due to his prime occurring in the peak of the steroid era), the Hall of Fame
Monitor and Standards both support the notion of Manny earning his way in. The two PED suspensions
in 2009 and 2011 (which ended his career) loom large as Manny needs another 42.5% of voters to
change their mind over the next two years.

**Carlos Beltran (1, 59, 136):** The HOF stats on Carlos Beltran’s page paint an accurate picture of
his career. With a low Black Ink score, but slightly above average Hall of Fame Monitor and
Standards scores, Beltran was never a dominant hitter but managed sustained success across a 20-year
career. At this point, Beltran has likely not made the Hall due to his status as the ringleader in
the 2017 Astros cheating scandal. As more time passes, the trash can incident will hopefully begin
to fade in voters’ minds and Beltran will make it on his fourth or fifth year on the ballot.

**Jimmy Rollins (7, 44, 105):** Jimmy Rollins fits right in the gray area when it comes to Hall of
Fame likelihood. While his Black Ink and Hall of Fame Standards scores clock in just below the
threshold, his Hall of Fame Monitor indicates he is deserving of heavy consideration at the least.
On top of his scores, Rollins was known for possessing winning attributes and a lack of
off-the-field issues. The voters do not regard Rollins as highly as the metrics do, but his case may
demand more attention than it has currently.

**Omar Vizquel (0, 44, 102.5):** The scores for Vizquel mirror Rollins’s scores very closely, and
Vizquel is a proven better defender than Rollins was during his career. However, Vizquel’s Hall
hopes have taken a nosedive in recent years after several stories relating to misconduct have been
released. Vizquel was no lock before the news, but now with domestic abuse and sexual harassment
allegations on his ledger, he stands virtually no chance of making his way in over the next three
rounds of voting.

**Andruw Jones (9, 42, 105.5):** Andruw Jones’s Hall of Fame scores portray a player with an outside
chance of making the Hall. Low Black Ink and Hall of Fame Standards display the strongest argument
against Druw finding his way into the Hall: lack of longevity. Jones’s numbers after his age-30
season see a sharp decline but voters are fans of his early power and elite defensive abilities in
one of the most important defensive positions. Needing 13.4% of voters to change their minds in two
years, it will be a nailbiter to see if Jones can get in.

**Bobby Abreu (4, 56, 99.5):** For a player who largely flew under the radar during his career,
Bobby Abreu has built a solid case for being considered. The HOF voters are unlikely to vote Abreu
in (14.8% of votes in year 5), but the metrics tell another story. Abreu’s stats over his career are
strong and uber-consistent, but not quite enough to merit true Hall of Fame talks. Abreu is the
textbook example of first-ballot Hall of Very Good.

**Chase Utley (3, 40, 84):** Chase Utley is an example of a player who was not dominant enough in
his prime nor great for a long enough time to make the Hall of Fame. Utley was really good from
2005-2009, but never a league leader (as represented in his low Black Ink score). The career stats
do not jump off the page either (shown by the low Hall of Fame Standards). However, Utley is a
champion and played on some strong Phillies teams, which contribute to his solid Hall of Fame
Monitor. Year one on the ballot led to 28.8% of votes, and it will be interesting to see if he makes
a leap in year two.

**Dustin Pedroia (11, 35, 95.5):** The HOF Stats Profile for Pedroia matches that of Utley’s nearly
perfectly, and their careers took similar turns. Pedroia’s Black Ink score outdoes Utley’s (still
not enough to get in most likely) which portrays the idea that at his peak Pedroia was slightly
better (as proven by his 2008 AL MVP win). However it was injuries that limited Pedroia’s Hall of
Fame potential as he struggled to play full seasons after the age of 30. Perhaps if he had played
longer, Pedroia would receive greater consideration for the Hall.

**Brian McCann (0, 36, 112):** During his peak, Brian McCann was a tremendous offensive catcher who
provided decent enough defense. While the numbers do not scream Hall of Fame-worthy, our metrics
believe McCann is much closer than what many would expect. Despite a 0 on the Black Ink test, the
HOF Monitor and Standards tests place him in a similar tier with his long-time NL East rival Chase
Utley and Dustin Pedroia, largely due to the value of his offense as a primary catcher.

**David Wright (0, 42, 89.5):** David Wright’s HOF Stats also paint a picture of a Hall of Very
Good-type player who is almost a lite version of Chase Utley, which makes sense when looking at
their voter turnouts in their first year on the Hall of Fame ballot (28.8% of votes vs. 6.2%).
Wright has a Black Ink score of 0, but had a solid prime for eight or nine years playing on great
Mets teams early in his career. Wright’s career ended abruptly, leading to high career averages and
therefore, a relatively strong HOF Standards score. However, like Pedroia, he was not able to play
long enough to warrant significant Hall of Fame consideration.

**Ian Kinsler (1, 38, 68.5):** Ian Kinsler was a strong second baseman for over ten years of his
career, but he starts a new tier of players that have no chance of making the Hall. None of
Kinsler’s HOF metrics are particularly convincing when it comes to making a case, but he should
garner enough consideration to stay on the ballot after year one.

**Hanley Ramirez (7, 43, 69.5):** Hanley Ramirez’s career got off to a hot start at shortstop for
the Florida Marlins, but his HOF case lacks the longevity and accolades to be seriously considered.
Ramirez is also on the ballot for the first time, and he will also be a name to keep an eye out for
a potential return next year.

**Curtis Granderson (7, 36, 72.5):** Despite some good years in Detroit and a few strong Yankees
seasons, Curtis Granderson is not quite good enough to make the HOF. It is a question whether his
three All-Star appearances will be enough to get 5% in year one.

**Torii Hunter (0, 43, 55):** After four years on the ballot, Torii Hunter can still only get 7.3%
of votes to be in the Hall. His HOF metrics reflect the fact that he will not make the HOF, but his
defensive abilities have given him enough respect to remain on the ballot for at least a fifth year.

**Russell Martin (0, 31, 53):** Russell Martin, like Brian McCann, gets a big boost in his HOF
metrics due to his status as a catcher, but his offensive numbers do not quite match up with
McCann’s. Our stats say McCann should receive more votes than Martin in their first year, but time
will tell whether or not this will be the case in 2025.

**Troy Tulowitzki (0, 38, 49.5):** Troy Tulowitzki, according to our metrics, is a lite version of
Hanley Ramirez. They both had dominant years as shortstops early in their careers (although Tulo’s
offensive numbers are helped by the Coors Field effect), followed by a steep fall off after the age
of 30. Tulo is another name to keep an eye on to see if he can make the 5% threshold.

<font size="5">Pitchers' Benchmarks: (Black Ink: 40, HOF Standards: 50, HOF Monitor: 100)</font>

**CC Sabathia (14, 47, 130):** Aside from Ichiro, CC Sabathia may be the most likely player on the
ballot to make the ballot. His metrics do not necessarily portray a first ballot Hall of Famer, but
for a player with a clean record like CC, they certainly point towards him making it sooner rather
than later. The Black Ink score is lower than one would expect, but CC was a longevity type of
pitcher more than a short dominant peak type. CC’s longevity garners him a high HOF Monitor score
that would assuredly earn him in a spot in the Hall. Perhaps aside from Billy Wagner, CC will be the
biggest question mark on the 2025 ballot.

**Andy Pettitte (4, 40, 121):** CC’s Yankees rotation counterpart, Andy Pettitte’s Hall of Fame
metrics stack up similarly to Sabathia. In all three scores, Pettitte ranks just below Sabathia
which would lead you to believe he would have acquired more than 13.5% of the vote in six years on
the ballot. The reason why Sabathia will fare better than Pettitte in HOF voting is Pettitte’s link
to HGH use in a 2007 report. Pettitte took an approach others have failed to use by apologizing for
his actions and he served no suspension for his actions. This apology has kept him in good graces
with baseball fans and writers, but not enough to warrant a HOF election, even if the stats say he
should probably be in.

**Francisco Rodriguez (9, 26, 124):** More so than any other player on this list, the metrics
support K-Rod’s Hall of Fame case to a degree the writers would never consider. During his peak,
Rodriguez was one of the most dominant closers of all time, pitching at a near Cy Young level for a
five season stretch. His dominance over this stretch and consistent good years for seven years after
leaving the Angels lead to a 124 score on the Hall of Fame Monitor, putting him well over the
benchmark for likely Hall of Famers. His Black Ink and HOF Standards scores do not match up with his
HOF Monitor, but regardless, the metrics say K-Rod should have a lot more than just 7.8% of votes in
year two on the ballot.

**Billy Wagner (0, 34, 104):** Billy Wagner may be the most intriguing case of all the balloted
players in 2025. As the only tenth year ballot member, Wagner needs to pick up an extra 1.2% of
votes in order to make the Hall in his final year. Compared to K-Rod, Wagner has a slightly better
HOF Standards score (still unlikely to make HOF with a 34) and a worse HOF Monitor score (barely
over the benchmark at 104). Our metrics say that Wagner is probably not quite good enough to get in,
especially compared to Rodriguez, but it would certainly not be an outcry if he did.

**Fernando Rodney (3, 18, 88):** Despite having a long and accomplished career, Fernando Rodney was
not a Hall of Fame-caliber pitcher out of the bullpen. His HOF Monitor score of 88 is very
competitive, but not representative of his other scores (3 and 18, respectively). There is a higher
barrier to entry for relief pitchers to make the Hall, and Fernando Rodney unfortunately does not
clear that barrier.

**Felix Hernandez (26, 30, 66):** Despite being one of the best pitchers of his era, King Felix’s
Hall of Fame chances remain very slim due to injuries that piled up after the age of 30. During his
peak from 2009-2015, King Felix was a consistent Cy Young-level pitcher, and that is well
represented by his relatively strong Black Ink score (26). However, weak seasons after 2015 and
early retirement limit Felix’s other HOF metrics from reaching true consideration. Felix will likely
retain his spot on the ballot like Mark Buehrle has, but the scores do not foresee much success
getting in.

**Mark Buehrle (12, 29, 51.5):** The voters are unlikely to put Mark Buehrle in the Hall of Fame, as
he has gathered just 8.3% of votes in four years on the ballot. However, Buehrle’s metrics are
eerily similar to Felix Hernandez’s. Both pitchers are classic Hall of Very Good arms, and their
consideration on the ballot is a respect to how good both were.
